### ISSUE TITLE
【2021-05-28】@media

### ISSUE THREAD

**Issue by F-star** [F-star/web-front-end-question#48]
`@media` 是媒体查询的一种。所谓媒体查询，可以根据设备的属性和参数来应用特定的样式。

常用简单适配 PC 端和手机端屏幕的写法：

```css
body {
  background-color: red;
}
@media (max-width: 980px) {
  body {
    background-color: blue;
  }
}
```

当屏幕宽度小于等于 980px 时，屏幕是蓝色的。大于则为红色（我瞎了）。如果希望在某个宽度区间（前后都是闭区间）应用特定的样式，可以使用 `@media (min-width: 768px) and (max-width: 991px) { ... }`。 `and` 将多个媒体查询规则组合，它们都为 true 时才会应用对应样式。
