### ISSUE TITLE
【2021-03-26】用CSS实现一个开关样式，hover时触发，滑块为正方形，具体大小可随意，如下图

### ISSUE THREAD

**Issue by F-star** [F-star/web-front-end-question#52]
![image](https://user-images.githubusercontent.com/18698939/127617931-02460f09-b93b-4a8c-bc9f-4d6a13319583.png)

**Comment by F-star** [comment]
## 实现

在线 demo：https://codepen.io/F-star/pen/abpNNYK

```html
<div class="container">
  <div class="switch"></div>
</div>
```

```css
.container {
  width: 200px;
}

.switch {
  position: relative;
  width: 100%;
  height: 56px;
  background-color: gray;
  transition: background-color .3s linear;
}
.switch::after {
  content: '';
  position: absolute;
  left: 0;
  margin: 3px;
  display: block;
  width: 50px;
  height: 50px;
  background-color: #fff;
  transition: left .3s linear;
}
.switch:hover {
  background-color: green;
}
.switch:hover::after {
  left: calc(100% - 56px);
}
```
