### ISSUE TITLE
【2021-04-19】CSS 三层描边实现

### ISSUE THREAD

**Issue by F-star** [F-star/web-front-end-question#76]
只能用一个元素实现。

demo：https://codepen.io/F-star/pen/XWpPBgQ?editors=1100

```css
.box {
  margin-top: 30px;
  margin-left: 30px;
  
  width: 50px;
  height: 50px;
  background-color: red;
  
  border: 10px solid green; /* 中间 */
  box-shadow: 0 0 0 10px blue, inset 0 0 0 10px yellow; /* 最外层和最内层 */
  /* box-shadow: 0 0 0 10px blue, inset 0 0 0 10px yellow, 0 0 0 20px gray; */ 
  /* 如果想再加一层描边，取消掉前面的 CSS 注释 */
}
```

核心是利用 box-shadow。这里简单讲下 box-shadow。bx-shadow 的多个属性依次为

- 阴影扩散方向。不设置表示向外，使用 inset 表示向内。
- x 偏移量（水平方向）
- y 偏移量（垂直方向）
- 阴影模糊半径（不能为负数）
- 阴影扩散半径（正值扩大，负值收缩）
- 颜色

中间的长度值可以不必全部指定，可以指定前几个。可以使用多个阴影值，用逗号分隔即可。让我们看会本题，设置好 border 描边后，我们可以用向外扩散和向内设置了扩散半径的 box-shadow 来实现另外两个描边。

扩展：因为 box-shadow 可以设置多个值，如果你还想再加一个描边，完全可以改为 `box-shadow: 0 0 0 10px blue, inset 0 0 0 10px yellow, 0 0 0 20px gray;`，这样又会多出一个最外层的灰色描边。
